export class CustomElementGlyphMappingService {
  constructor() {
    this.customElementNodeNameToGlyphNameMap = new Map();
    this.customElementNodeNameToGlyphNameMap.set('X-ISON', 'ison');
    this.customElementNodeNameToGlyphNameMap.set('X-OLIGON', 'oligon');
    this.customElementNodeNameToGlyphNameMap.set(
      'X-OLIGON-KENTIMA-MIDDLE',
      'oligonKentimaMiddle',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-OLIGON-KENTIMA-BELOW',
      'oligonKentimaBelow',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-OLIGON-KENTIMA-ABOVE',
      'oligonKentimaAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-OLIGON-YPSILI-RIGHT',
      'oligonYpsiliRight',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-OLIGON-YPSILI-LEFT',
      'oligonYpsiliLeft',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-OLIGON-KENTIMA-YPSILI-RIGHT',
      'oligonKentimaYpsiliRight',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-OLIGON-KENTIMA-YPSILI-MIDDLE',
      'oligonKentimaYpsiliMiddle',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-OLIGON-DOUBLE-YPSILI',
      'oligonDoubleYpsili',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-OLIGON-KENTIMATA-DOUBLE-YPSILI',
      'oligonKentimataDoubleYpsili',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-OLIGON-KENTIMA-DOUBLE-YPSILI-RIGHT',
      'oligonKentimaDoubleYpsiliRight',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-OLIGON-KENTIMA-DOUBLE-YPSILI-LEFT',
      'oligonKentimaDoubleYpsiliLeft',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-OLIGON-TRIPLE-YPSILI',
      'oligonTripleYpsili',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-OLIGON-KENTIMATA-TRIPLE-YPSILI',
      'oligonKentimataTripleYpsili',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-OLIGON-KENTIMA-TRIPLE-YPSILI',
      'oligonKentimaTripleYpsili',
    );
    this.customElementNodeNameToGlyphNameMap.set('X-OLIGON-ISON', 'oligonIson');
    this.customElementNodeNameToGlyphNameMap.set(
      'X-OLIGON-APOSTROFOS',
      'oligonApostrofos',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-OLIGON-YPORROI',
      'oligonYporroi',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-OLIGON-ELAFRON',
      'oligonElafron',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-OLIGON-ELAFRON-APOSTROFOS',
      'oligonElafronApostrofos',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-OLIGON-CHAMILI',
      'oligonChamili',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-ISON-APOSTROFOS',
      'isonApostrofos',
    );
    this.customElementNodeNameToGlyphNameMap.set('X-APOSTROFOS', 'apostrofos');
    this.customElementNodeNameToGlyphNameMap.set(
      'X-APOSTROFOS-SYNDESMOS',
      'apostrofosSyndesmos',
    );
    this.customElementNodeNameToGlyphNameMap.set('X-YPORROI', 'yporroi');
    this.customElementNodeNameToGlyphNameMap.set('X-ELAFRON', 'elafron');
    this.customElementNodeNameToGlyphNameMap.set(
      'X-RUNNING-ELAFRON',
      'runningElafron',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-ELAFRON-APOSTROFOS',
      'elafronApostrofos',
    );
    this.customElementNodeNameToGlyphNameMap.set('X-CHAMILI', 'chamili');
    this.customElementNodeNameToGlyphNameMap.set(
      'X-CHAMILI-APOSTROFOS',
      'chamiliApostrofos',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-CHAMILI-ELAFRON',
      'chamiliElafron',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-CHAMILI-ELAFRON-APOSTROFOS',
      'chamiliElafronApostrofos',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-DOUBLE-CHAMILI',
      'doubleChamili',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-DOUBLE-CHAMILI-APOSTROFOS',
      'doubleChamiliApostrofos',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-DOUBLE-CHAMILI-ELAFRON',
      'doubleChamiliElafron',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-DOUBLE-CHAMILI-ELAFRON-APOSTROFOS',
      'doubleChamiliElafronApostrofos',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-TRIPLE-CHAMILI',
      'tripleChamili',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-PETASTI-ISON',
      'petastiIson',
    );
    this.customElementNodeNameToGlyphNameMap.set('X-PETASTI', 'petasti');
    this.customElementNodeNameToGlyphNameMap.set(
      'X-PETASTI-OLIGON',
      'petastiOligon',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-PETASTI-KENTIMA',
      'petastiKentima',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-PETASTI-YPSILI-RIGHT',
      'petastiYpsiliRight',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-PETASTI-YPSILI-LEFT',
      'petastiYpsiliLeft',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-PETASTI-KENTIMA-YPSILI-RIGHT',
      'petastiKentimaYpsiliRight',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-PETASTI-KENTIMA-YPSILI-MIDDLE',
      'petastiKentimaYpsiliMiddle',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-PETASTI-DOUBLE-YPSILI',
      'petastiDoubleYpsili',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-PETASTI-KENTIMATA-DOUBLE-YPSILI',
      'petastiKentimataDoubleYpsili',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-PETASTI-KENTIMA-DOUBLE-YPSILI-RIGHT',
      'petastiKentimaDoubleYpsiliRight',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-PETASTI-KENTIMA-DOUBLE-YPSILI-LEFT',
      'petastiKentimaDoubleYpsiliLeft',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-PETASTI-TRIPLE-YPSILI',
      'petastiTripleYpsili',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-PETASTI-KENTIMATA-TRIPLE-YPSILI',
      'petastiKentimataTripleYpsili',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-PETASTI-KENTIMA-TRIPLE-YPSILI',
      'petastiKentimaTripleYpsili',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-PETASTI-APOSTROFOS',
      'petastiApostrofos',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-PETASTI-YPORROI',
      'petastiYporroi',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-PETASTI-ELAFRON',
      'petastiElafron',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-PETASTI-RUNNING-ELAFRON',
      'petastiRunningElafron',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-PETASTI-ELAFRON-APOSTROFOS',
      'petastiElafronApostrofos',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-PETASTI-CHAMILI',
      'petastiChamili',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-PETASTI-CHAMILI-APOSTROFOS',
      'petastiChamiliApostrofos',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-PETASTI-CHAMILI-ELAFRON',
      'petastiChamiliElafron',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-PETASTI-CHAMILI-ELAFRON-APOSTROFOS',
      'petastiChamiliElafronApostrofos',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-PETASTI-DOUBLE-CHAMILI',
      'petastiDoubleChamili',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-PETASTI-DOUBLE-CHAMILI-APOSTROFOS',
      'petastiDoubleChamiliApostrofos',
    );
    this.customElementNodeNameToGlyphNameMap.set('X-KENTIMA', 'kentima');
    this.customElementNodeNameToGlyphNameMap.set('X-KENTIMATA', 'kentimata');
    this.customElementNodeNameToGlyphNameMap.set(
      'X-OLIGON-KENTIMATA-BELOW',
      'oligonKentimataBelow',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-OLIGON-KENTIMATA-ABOVE',
      'oligonKentimataAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-OLIGON-ISON-KENTIMATA',
      'oligonIsonKentimata',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-OLIGON-KENTIMA-MIDDLE-KENTIMATA',
      'oligonKentimaMiddleKentimata',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-OLIGON-YPSILI-RIGHT-KENTIMATA',
      'oligonYpsiliRightKentimata',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-OLIGON-YPSILI-LEFT-KENTIMATA',
      'oligonYpsiliLeftKentimata',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-OLIGON-APOSTROFOS-KENTIMATA',
      'oligonApostrofosKentimata',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-OLIGON-YPORROI-KENTIMATA',
      'oligonYporroiKentimata',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-OLIGON-ELAFRON-KENTIMATA',
      'oligonElafronKentimata',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-OLIGON-RUNNING-ELAFRON-KENTIMATA',
      'oligonRunningElafronKentimata',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-OLIGON-ELAFRON-APOSTROFOS-KENTIMATA',
      'oligonElafronApostrofosKentimata',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-OLIGON-CHAMILI-KENTIMATA',
      'oligonChamiliKentimata',
    );
    this.customElementNodeNameToGlyphNameMap.set('X-VAREIA', 'vareia');
    this.customElementNodeNameToGlyphNameMap.set('X-PSIFISTON', 'psifiston');
    this.customElementNodeNameToGlyphNameMap.set('X-ANTIKENOMA', 'antikenoma');
    this.customElementNodeNameToGlyphNameMap.set('X-OMALON', 'omalon');
    this.customElementNodeNameToGlyphNameMap.set(
      'X-OMALON-CONNECTING',
      'omalonConnecting',
    );
    this.customElementNodeNameToGlyphNameMap.set('X-HETERON', 'heteron');
    this.customElementNodeNameToGlyphNameMap.set(
      'X-HETERON-CONNECTING',
      'heteronConnecting',
    );
    this.customElementNodeNameToGlyphNameMap.set('X-ENDOFONON', 'endofonon');
    this.customElementNodeNameToGlyphNameMap.set('X-YFEN-ABOVE', 'yfenAbove');
    this.customElementNodeNameToGlyphNameMap.set('X-YFEN-BELOW', 'yfenBelow');
    this.customElementNodeNameToGlyphNameMap.set('X-STAVROS', 'stavros');
    this.customElementNodeNameToGlyphNameMap.set('X-BREATH', 'breath');
    this.customElementNodeNameToGlyphNameMap.set(
      'X-KLASMA-ABOVE',
      'klasmaAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-KLASMA-BELOW',
      'klasmaBelow',
    );
    this.customElementNodeNameToGlyphNameMap.set('X-APLI', 'apli');
    this.customElementNodeNameToGlyphNameMap.set('X-DIPLI', 'dipli');
    this.customElementNodeNameToGlyphNameMap.set('X-TRIPLI', 'tripli');
    this.customElementNodeNameToGlyphNameMap.set('X-TETRAPLI', 'tetrapli');
    this.customElementNodeNameToGlyphNameMap.set('X-KORONIS', 'koronis');
    this.customElementNodeNameToGlyphNameMap.set('X-LEIMMA1', 'leimma1');
    this.customElementNodeNameToGlyphNameMap.set('X-LEIMMA2', 'leimma2');
    this.customElementNodeNameToGlyphNameMap.set('X-LEIMMA3', 'leimma3');
    this.customElementNodeNameToGlyphNameMap.set('X-LEIMMA4', 'leimma4');
    this.customElementNodeNameToGlyphNameMap.set('X-LEIMMA-DOT', 'leimmaDot');
    this.customElementNodeNameToGlyphNameMap.set(
      'X-GORGON-ABOVE',
      'gorgonAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-GORGON-BELOW',
      'gorgonBelow',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-GORGON-DOTTED-LEFT',
      'gorgonDottedLeft',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-GORGON-DOTTED-RIGHT',
      'gorgonDottedRight',
    );
    this.customElementNodeNameToGlyphNameMap.set('X-DIGORGON', 'digorgon');
    this.customElementNodeNameToGlyphNameMap.set(
      'X-DIGORGON-DOTTED-LEFT-BELOW',
      'digorgonDottedLeftBelow',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-DIGORGON-DOTTED-LEFT-ABOVE',
      'digorgonDottedLeftAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-DIGORGON-DOTTED-RIGHT',
      'digorgonDottedRight',
    );
    this.customElementNodeNameToGlyphNameMap.set('X-TRIGORGON', 'trigorgon');
    this.customElementNodeNameToGlyphNameMap.set(
      'X-TRIGORGON-DOTTED-LEFT-BELOW',
      'trigorgonDottedLeftBelow',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-TRIGORGON-DOTTED-LEFT-ABOVE',
      'trigorgonDottedLeftAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-TRIGORGON-DOTTED-RIGHT',
      'trigorgonDottedRight',
    );
    this.customElementNodeNameToGlyphNameMap.set('X-ARGON', 'argon');
    this.customElementNodeNameToGlyphNameMap.set('X-DIARGON', 'diargon');
    this.customElementNodeNameToGlyphNameMap.set('X-TRIARGON', 'triargon');
    this.customElementNodeNameToGlyphNameMap.set(
      'X-GORGON-SECONDARY',
      'gorgonSecondary',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-GORGON-DOTTED-LEFT-SECONDARY',
      'gorgonDottedLeftSecondary',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-GORGON-DOTTED-RIGHT-SECONDARY',
      'gorgonDottedRightSecondary',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-DIGORGON-SECONDARY',
      'digorgonSecondary',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-DIGORGON-DOTTED-LEFT-BELOW-SECONDARY',
      'digorgonDottedLeftBelowSecondary',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-DIGORGON-DOTTED-RIGHT-SECONDARY',
      'digorgonDottedRightSecondary',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-TRIGORGON-SECONDARY',
      'trigorgonSecondary',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-TRIGORGON-DOTTED-LEFT-BELOW-SECONDARY',
      'trigorgonDottedLeftBelowSecondary',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-TRIGORGON-DOTTED-RIGHT-SECONDARY',
      'trigorgonDottedRightSecondary',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-AGOGI-POLI-ARGI',
      'agogiPoliArgi',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-AGOGI-ARGOTERI',
      'agogiArgoteri',
    );
    this.customElementNodeNameToGlyphNameMap.set('X-AGOGI-ARGI', 'agogiArgi');
    this.customElementNodeNameToGlyphNameMap.set(
      'X-AGOGI-METRIA',
      'agogiMetria',
    );
    this.customElementNodeNameToGlyphNameMap.set('X-AGOGI-MESI', 'agogiMesi');
    this.customElementNodeNameToGlyphNameMap.set('X-AGOGI-GORGI', 'agogiGorgi');
    this.customElementNodeNameToGlyphNameMap.set(
      'X-AGOGI-GORGOTERI',
      'agogiGorgoteri',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-AGOGI-POLI-GORGI',
      'agogiPoliGorgi',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-AGOGI-POLI-ARGI-ABOVE',
      'agogiPoliArgiAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-AGOGI-ARGOTERI-ABOVE',
      'agogiArgoteriAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-AGOGI-ARGI-ABOVE',
      'agogiArgiAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-AGOGI-METRIA-ABOVE',
      'agogiMetriaAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-AGOGI-MESI-ABOVE',
      'agogiMesiAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-AGOGI-GORGI-ABOVE',
      'agogiGorgiAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-AGOGI-GORGOTERI-ABOVE',
      'agogiGorgoteriAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-AGOGI-POLI-GORGI-ABOVE',
      'agogiPoliGorgiAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-NOTE-ZO-LOW',
      'martyriaNoteZoLow',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-NOTE-NI-LOW',
      'martyriaNoteNiLow',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-NOTE-PA-LOW',
      'martyriaNotePaLow',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-NOTE-VOU-LOW',
      'martyriaNoteVouLow',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-NOTE-GA-LOW',
      'martyriaNoteGaLow',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-NOTE-DI-LOW',
      'martyriaNoteDiLow',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-NOTE-KE-LOW',
      'martyriaNoteKeLow',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-NOTE-ZO',
      'martyriaNoteZo',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-NOTE-NI',
      'martyriaNoteNi',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-NOTE-PA',
      'martyriaNotePa',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-NOTE-VOU',
      'martyriaNoteVou',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-NOTE-GA',
      'martyriaNoteGa',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-NOTE-DI',
      'martyriaNoteDi',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-NOTE-KE',
      'martyriaNoteKe',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-NOTE-ZO-HIGH',
      'martyriaNoteZoHigh',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-NOTE-NI-HIGH',
      'martyriaNoteNiHigh',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-NOTE-PA-HIGH',
      'martyriaNotePaHigh',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-NOTE-VOU-HIGH',
      'martyriaNoteVouHigh',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-NOTE-GA-HIGH',
      'martyriaNoteGaHigh',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-NOTE-DI-HIGH',
      'martyriaNoteDiHigh',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-NOTE-KE-HIGH',
      'martyriaNoteKeHigh',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-TICK',
      'martyriaTick',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-ZO-BELOW',
      'martyriaZoBelow',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-DELTA-BELOW',
      'martyriaDeltaBelow',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-ALPHA-BELOW',
      'martyriaAlphaBelow',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-LEGETOS-BELOW',
      'martyriaLegetosBelow',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-NANA-BELOW',
      'martyriaNanaBelow',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-DELTA-DOTTED-BELOW',
      'martyriaDeltaDottedBelow',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-ALPHA-DOTTED-BELOW',
      'martyriaAlphaDottedBelow',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-HARD-CHROMATIC-PA-BELOW',
      'martyriaHardChromaticPaBelow',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-HARD-CHROMATIC-DI-BELOW',
      'martyriaHardChromaticDiBelow',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-SOFT-CHROMATIC-DI-BELOW',
      'martyriaSoftChromaticDiBelow',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-SOFT-CHROMATIC-KE-BELOW',
      'martyriaSoftChromaticKeBelow',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-ZYGOS-BELOW',
      'martyriaZygosBelow',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-ZO-ABOVE',
      'martyriaZoAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-DELTA-ABOVE',
      'martyriaDeltaAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-ALPHA-ABOVE',
      'martyriaAlphaAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-LEGETOS-ABOVE',
      'martyriaLegetosAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-NANA-ABOVE',
      'martyriaNanaAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-DELTA-DOTTED-ABOVE',
      'martyriaDeltaDottedAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-ALPHA-DOTTED-ABOVE',
      'martyriaAlphaDottedAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-HARD-CHROMATIC-PA-ABOVE',
      'martyriaHardChromaticPaAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-HARD-CHROMATIC-DI-ABOVE',
      'martyriaHardChromaticDiAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-SOFT-CHROMATIC-DI-ABOVE',
      'martyriaSoftChromaticDiAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-SOFT-CHROMATIC-KE-ABOVE',
      'martyriaSoftChromaticKeAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MARTYRIA-ZYGOS-ABOVE',
      'martyriaZygosAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-FTHORA-DIATONIC-NI-LOW-ABOVE',
      'fthoraDiatonicNiLowAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-FTHORA-DIATONIC-PA-ABOVE',
      'fthoraDiatonicPaAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-FTHORA-DIATONIC-VOU-ABOVE',
      'fthoraDiatonicVouAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-FTHORA-DIATONIC-GA-ABOVE',
      'fthoraDiatonicGaAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-FTHORA-DIATONIC-DI-ABOVE',
      'fthoraDiatonicDiAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-FTHORA-DIATONIC-KE-ABOVE',
      'fthoraDiatonicKeAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-FTHORA-DIATONIC-ZO-ABOVE',
      'fthoraDiatonicZoAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-FTHORA-DIATONIC-NI-HIGH-ABOVE',
      'fthoraDiatonicNiHighAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-FTHORA-HARD-CHROMATIC-PA-ABOVE',
      'fthoraHardChromaticPaAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-FTHORA-HARD-CHROMATIC-DI-ABOVE',
      'fthoraHardChromaticDiAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-FTHORA-SOFT-CHROMATIC-DI-ABOVE',
      'fthoraSoftChromaticDiAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-FTHORA-SOFT-CHROMATIC-KE-ABOVE',
      'fthoraSoftChromaticKeAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-FTHORA-ENHARMONIC-ABOVE',
      'fthoraEnharmonicAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-CHROA-ZYGOS-ABOVE',
      'chroaZygosAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-CHROA-KLITON-ABOVE',
      'chroaKlitonAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-CHROA-SPATHI-ABOVE',
      'chroaSpathiAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-FTHORA-DIATONIC-NI-LOW-BELOW',
      'fthoraDiatonicNiLowBelow',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-FTHORA-DIATONIC-PA-BELOW',
      'fthoraDiatonicPaBelow',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-FTHORA-DIATONIC-VOU-BELOW',
      'fthoraDiatonicVouBelow',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-FTHORA-DIATONIC-GA-BELOW',
      'fthoraDiatonicGaBelow',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-FTHORA-DIATONIC-DI-BELOW',
      'fthoraDiatonicDiBelow',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-FTHORA-DIATONIC-KE-BELOW',
      'fthoraDiatonicKeBelow',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-FTHORA-DIATONIC-ZO-BELOW',
      'fthoraDiatonicZoBelow',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-FTHORA-DIATONIC-NI-HIGH-BELOW',
      'fthoraDiatonicNiHighBelow',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-FTHORA-HARD-CHROMATIC-PA-BELOW',
      'fthoraHardChromaticPaBelow',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-FTHORA-HARD-CHROMATIC-DI-BELOW',
      'fthoraHardChromaticDiBelow',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-FTHORA-SOFT-CHROMATIC-DI-BELOW',
      'fthoraSoftChromaticDiBelow',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-FTHORA-SOFT-CHROMATIC-KE-BELOW',
      'fthoraSoftChromaticKeBelow',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-FTHORA-ENHARMONIC-BELOW',
      'fthoraEnharmonicBelow',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-CHROA-ZYGOS-BELOW',
      'chroaZygosBelow',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-CHROA-KLITON-BELOW',
      'chroaKlitonBelow',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-CHROA-SPATHI-BELOW',
      'chroaSpathiBelow',
    );
    this.customElementNodeNameToGlyphNameMap.set('X-DIESIS2', 'diesis2');
    this.customElementNodeNameToGlyphNameMap.set('X-DIESIS4', 'diesis4');
    this.customElementNodeNameToGlyphNameMap.set('X-DIESIS6', 'diesis6');
    this.customElementNodeNameToGlyphNameMap.set('X-DIESIS8', 'diesis8');
    this.customElementNodeNameToGlyphNameMap.set(
      'X-DIESIS-GENIKI-ABOVE',
      'diesisGenikiAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-DIESIS-GENIKI-BELOW',
      'diesisGenikiBelow',
    );
    this.customElementNodeNameToGlyphNameMap.set('X-YFESIS2', 'yfesis2');
    this.customElementNodeNameToGlyphNameMap.set('X-YFESIS4', 'yfesis4');
    this.customElementNodeNameToGlyphNameMap.set('X-YFESIS6', 'yfesis6');
    this.customElementNodeNameToGlyphNameMap.set('X-YFESIS8', 'yfesis8');
    this.customElementNodeNameToGlyphNameMap.set(
      'X-YFESIS-GENIKI-ABOVE',
      'yfesisGenikiAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-YFESIS-GENIKI-BELOW',
      'yfesisGenikiBelow',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-BARLINE-SINGLE',
      'barlineSingle',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-BARLINE-DOUBLE',
      'barlineDouble',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-BARLINE-THESEOS',
      'barlineTheseos',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-BARLINE-SHORT-SINGLE',
      'barlineShortSingle',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-BARLINE-SHORT-DOUBLE',
      'barlineShortDouble',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-BARLINE-SHORT-THESEOS',
      'barlineShortTheseos',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MEASURE-NUMBER2',
      'measureNumber2',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MEASURE-NUMBER3',
      'measureNumber3',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MEASURE-NUMBER4',
      'measureNumber4',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MEASURE-NUMBER5',
      'measureNumber5',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MEASURE-NUMBER6',
      'measureNumber6',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MEASURE-NUMBER7',
      'measureNumber7',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MEASURE-NUMBER8',
      'measureNumber8',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-NOTE-INDICATOR-NI',
      'noteIndicatorNi',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-NOTE-INDICATOR-PA',
      'noteIndicatorPa',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-NOTE-INDICATOR-VOU',
      'noteIndicatorVou',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-NOTE-INDICATOR-GA',
      'noteIndicatorGa',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-NOTE-INDICATOR-DI',
      'noteIndicatorDi',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-NOTE-INDICATOR-KE',
      'noteIndicatorKe',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-NOTE-INDICATOR-ZO',
      'noteIndicatorZo',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-ISON-INDICATOR-UNISON',
      'isonIndicatorUnison',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-ISON-INDICATOR-DI-LOW',
      'isonIndicatorDiLow',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-ISON-INDICATOR-KE-LOW',
      'isonIndicatorKeLow',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-ISON-INDICATOR-ZO',
      'isonIndicatorZo',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-ISON-INDICATOR-NI',
      'isonIndicatorNi',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-ISON-INDICATOR-PA',
      'isonIndicatorPa',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-ISON-INDICATOR-VOU',
      'isonIndicatorVou',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-ISON-INDICATOR-GA',
      'isonIndicatorGa',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-ISON-INDICATOR-DI',
      'isonIndicatorDi',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-ISON-INDICATOR-KE',
      'isonIndicatorKe',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-ISON-INDICATOR-ZO-HIGH',
      'isonIndicatorZoHigh',
    );
    this.customElementNodeNameToGlyphNameMap.set('X-GORTHMIKON', 'gorthmikon');
    this.customElementNodeNameToGlyphNameMap.set('X-PELASTIKON', 'pelastikon');
    this.customElementNodeNameToGlyphNameMap.set('X-MODE-FIRST', 'modeFirst');
    this.customElementNodeNameToGlyphNameMap.set('X-MODE-SECOND', 'modeSecond');
    this.customElementNodeNameToGlyphNameMap.set('X-MODE-THIRD', 'modeThird');
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MODE-THIRD-NANA',
      'modeThirdNana',
    );
    this.customElementNodeNameToGlyphNameMap.set('X-MODE-FOURTH', 'modeFourth');
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MODE-LEGETOS',
      'modeLegetos',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MODE-PLAGAL-FIRST',
      'modePlagalFirst',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MODE-PLAGAL-SECOND',
      'modePlagalSecond',
    );
    this.customElementNodeNameToGlyphNameMap.set('X-MODE-VARYS', 'modeVarys');
    this.customElementNodeNameToGlyphNameMap.set('X-MODE-VARYS2', 'modeVarys2');
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MODE-PLAGAL-FOURTH',
      'modePlagalFourth',
    );
    this.customElementNodeNameToGlyphNameMap.set('X-MODE-NI', 'modeNi');
    this.customElementNodeNameToGlyphNameMap.set('X-MODE-PA', 'modePa');
    this.customElementNodeNameToGlyphNameMap.set('X-MODE-VOU', 'modeVou');
    this.customElementNodeNameToGlyphNameMap.set('X-MODE-GA', 'modeGa');
    this.customElementNodeNameToGlyphNameMap.set('X-MODE-DI', 'modeDi');
    this.customElementNodeNameToGlyphNameMap.set('X-MODE-KE', 'modeKe');
    this.customElementNodeNameToGlyphNameMap.set('X-MODE-ZO', 'modeZo');
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MODE-OLIGON-KENTIMA-ABOVE',
      'modeOligonKentimaAbove',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MODE-OLIGON-YPSILI',
      'modeOligonYpsili',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MODE-ELAFRON',
      'modeElafron',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MODE-RUNNING-ELAFRON',
      'modeRunningElafron',
    );
    this.customElementNodeNameToGlyphNameMap.set('X-MODE-PLAGAL', 'modePlagal');
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MODE-WORD-ECHOS',
      'modeWordEchos',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MODE-WORD-VARYS',
      'modeWordVarys',
    );
    this.customElementNodeNameToGlyphNameMap.set('X-MODE-ALPHA', 'modeAlpha');
    this.customElementNodeNameToGlyphNameMap.set('X-MODE-BETA', 'modeBeta');
    this.customElementNodeNameToGlyphNameMap.set('X-MODE-GAMMA', 'modeGamma');
    this.customElementNodeNameToGlyphNameMap.set('X-MODE-DELTA', 'modeDelta');
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MODE-ALPHA-CAPITAL',
      'modeAlphaCapital',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MODE-BETA-CAPITAL',
      'modeBetaCapital',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MODE-GAMMA-CAPITAL',
      'modeGammaCapital',
    );
    this.customElementNodeNameToGlyphNameMap.set(
      'X-MODE-DELTA-CAPITAL',
      'modeDeltaCapital',
    );
  }

  getGlyphNameFromNodeName(nodeName) {
    return this.customElementNodeNameToGlyphNameMap.get(nodeName);
  }
}
